name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-2.7-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-2.7-
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get -y install libgsl-dev
        bundle install --path=vendor/bundle
        bundle clean
        npm install
    - name: Prettier check
      run: |
        npx prettier --check .
    - name: Prepare build
      if: github.ref == 'refs/heads/master'
      run: |
        git clone --depth=1 --branch=gh-pages --single-branch --no-checkout \
          "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" \
          _site
    - name: Build site
      run: |
        bundle exec jekyll build --trace --profile
        : > _site/.nojekyll
        echo -n 'beta.ustclug.org' > _site/CNAME
      env:
        JEKYLL_ENV: production
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      run: |
        CINFO="$(git log -1 --pretty="%an: [%h] %s")"
        pushd _site/ &>/dev/null
        echo -n lug.ustc.edu.cn > CNAME
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "Auto deploy from GitHub Actions build ${GITHUB_RUN_NUMBER}" \
          -m "$CINFO"
        git push
        popd &>/dev/null
    - name: Call webhook
      if: 'github.repository == "ustclug/website" && github.ref == "refs/heads/master"'
      env:
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      run: ruby _scripts/webhook.rb
